"""Build samples/example_output.json from real collector output only.

Every value in the generated file comes from a captured Bright Data response in
this directory. Nothing is hand-written, so the submitted example output cannot
drift away from what the collector actually returned.

    python samples/build_example_output.py

Reads whichever of these exist and uses the most recent:
    run_shopalto.json              pre-heal run  (product_name, price)
    run_shopalto_after_heal.json   post-heal run (+ description, image, rating)
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
COLLECTOR_ID = "c_mt0hvfomh2bmennhd"


def load(name: str):
    path = HERE / name
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8-sig"))


def rows_of(payload) -> list[dict]:
    if payload is None:
        return []
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for key in ("data", "rows", "result", "preview_result"):
            value = payload.get(key)
            if isinstance(value, list):
                return value
    return []


def field_names(rows: list[dict]) -> list[str]:
    names: list[str] = []
    for row in rows:
        for key in row:
            if key not in names:
                names.append(key)
    return names


def main() -> None:
    before = rows_of(load("run_shopalto.json"))
    after = rows_of(load("run_shopalto_after_heal.json"))
    create = load("create_shopalto.json") or {}

    preview = rows_of(load("heal_shopalto.json"))
    stage = "post_heal" if after else "pre_heal"

    before_fields = field_names(before)
    after_fields = field_names(after)
    preview_fields = field_names(preview)

    gained = [f for f in after_fields if f not in before_fields]
    regressed = [f for f in before_fields if f not in after_fields]
    never_delivered = [
        f for f in preview_fields if f not in before_fields and f not in after_fields
    ]

    document = {
        "product": "Driftwatch",
        "note": (
            "Generated by samples/build_example_output.py from captured Bright Data "
            "responses in this directory. No hand-written values."
        ),
        "collector": {
            "id": COLLECTOR_ID,
            "name": create.get("name", "shopalto_products"),
            "created_at": create.get("created_at"),
            "control_panel": create.get("view_url"),
        },
        "stage": stage,
        "schema_change": {
            "fields_before_heal": before_fields,
            "fields_in_heal_preview": preview_fields,
            "fields_after_heal": after_fields,
            "fields_gained": gained,
            "fields_regressed": regressed,
            "fields_never_delivered": never_delivered,
            "note": (
                "fields_regressed were returned before the heal and are absent after "
                "it. fields_never_delivered appeared in the heal preview but in no "
                "live run. The preview showed every requested field, the live run did "
                "not, and that gap is what this project exists to catch."
            ),
        },
        "row_count": len(before) + len(after),
        "rows": {"before_heal": before, "after_heal": after},
    }

    out = HERE / "example_output.json"
    out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(
        f"wrote {out} stage={stage} gained={gained} "
        f"regressed={regressed} never_delivered={never_delivered}"
    )


if __name__ == "__main__":
    main()
